# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googleLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for googleLogin
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'

end
