# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ios1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios1
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'

end
